### ISSUE TITLE
Active speaker view

### ISSUE THREAD

**Issue by sampaccoud** [Anapher/Strive#4]
We tried openstrive with 10+ persons and were surprise that on the "Active Speaker" view, only 2 videos are shown in addition to the active speaker. Is it intentional? If yes can you clarify why this decision?

Also we would like to continue our tests and eventually use it in a network of universities we federate. I did not find any blog post explaining what are your objectives and how you plan to organize the project. We would like to collaborate and help. Can you elaborate?

**Comment by Anapher** [comment]
Hey,
after I finished the whiteboard, I definitely want to work on the grid, screen share and active speaker scene. I totally agree with you that currently, this is not implemented very well.
So yes, it is intentional that the active speaker scene does currently display only a few participants but I want to clarify that I wanted to push Strive to a preview phase were the core concepts are available. Changing the active speaker scene will be very easy if I have a good concept.
Here, I'm also open for suggestions. In Zoom, multiple participants (~10) are displayed above the current content. I think that displaying them above is also a good idea, as in the active speaker scene of Strive, the small participant tiles are overlapped by the controls.
The next question will be if the active speaker and the screen scene should be "merged". Currently in the screen scene, one to three participants overlay the screen or, if necessary, the presenter moves above the chat. Maybe that should also be configurable, so the presenter should decide whether a maximum screen size is prefferred or other participants should be visible.

First of all it is very nice to hear that you consider to use Strive. If you want, we can also exchange contact information so I can provide fast support to you. You can find my email address in my github bio.
It would be really nice to have Strive as a competitor to BigBlueButton. Strive will always stay free and open source. Actually, my objectives with Strive are to have a nice project I can work on and learn new stuff.

Actually, I did not yet think a lot about the organization of the project. Of course I will accept collaboration. I'm also always open for new ideas or suggestions to reconsider decisions.
